### ISSUE TITLE
unresolved import 'microbit'

### ISSUE THREAD

**Issue by buglovebug** [PhonicCanine/vscode-microbit#1]
hi, nice to meet you

when I build python file, vscode have "unresolved import 'microbit' " problem, how can I import microbit sub library?

**Comment by PhonicCanine** [comment]
Hi!

So, the microbit sub library will only work when the code is actually running on a micro:bit. The folder in this extension exists in order to give intellisense feedback to code you're writing.

Let me know if this is not what you were asking about though.

Thanks for using the extension!
