### ISSUE TITLE
Flashing script and module

### ISSUE THREAD

**Issue by oivron** [PhonicCanine/vscode-microbit#4]
This is great. We use VSCode with this extension to teach blind children programming using the micro:bit. We prefer VSCode because of its excellent support for screen readers.

I need to write a module for the micro:bit accessory Bit:bot XL. But I can't figure out how to transfer both a Python script and a module to the micro:bit at the same time. Please see my full post at [https://stackoverflow.com/questions/60451535/how-do-i-transfer-my-python-script-including-my-module-to-the-microbit](url)

**Comment by mucolon** [comment]
I would be interested if there's a way to do this also on VS Code. I know you can do it on micro:bit's online python editor and I think it's also possible using the mu editor.

**Comment by oivron** [comment]
Check out this [question on stackoverflow](https://stackoverflow.com/questions/52782520/flash-microbit-embedding-a-class-py-file). See last comment.

**Comment by mucolon** [comment]
Awesome! Thank you for linking this.

@PhonicCanine If you have some time on your hands, it would be great if you can add the `ufs` option to your extension.

**Comment by PhonicCanine** [comment]
I've added a `Put this file onto the attached micro:bit` command (in the command palette, in version 0.3.0), that will run `ufs put filename` on the currently open file. Please let me know if this is not how you'd like the feature implemented. It should work fine currently.
Additionally, I've added a `Clear files on the attached micro:bit` command which will effectively `rm -rf` the filesystem.
I hope this can be useful; and I apologize for taking so long. Thank you for using the extension, and it's great to have played some part in such valuable social good. Apologies again for taking so long.

And again, please let me know if you'd like the feature implemented in some other way.
